### ISSUE TITLE
key binding conflict withg Ctrl+C

### ISSUE THREAD

**Issue by crystalgreen** [SeungukShin/org-code#1]
The command ´org-code.set.state` has a key binding `ctrl+c ctrl+t` which breaks the VS Code standard binding `ctrl+c` for copy. Of course one can remove your binding in the preferences but it is not so easy to figure out why one has to do this.
I propose you chose a binding that does not conflict with VS Code defaults.

**Comment by seungukshin** [comment]
Dear crystalgreen,
Thank you for your feedback and very sorry for terribly late response.
The primary purpose of this extension is using the same keybindings with emacs. That's why I use keybindings which start with `ctrl+c` even it breaks vscode's standard keybindings.
Thank you.
Best regards,
Seunguk Shin
